In [4]:
# 這裡import ... as ... => 是說導入一個模組(module、library都可以)，就如同java中告訴它要Reference的class是誰
# ，然後後面的as就只是alias
import numpy as np

# 所以這邊的np.array()，並不是「object類別的呼叫function」，而是!!「類別類(這邊應該會說包類)」
ary = np.array([0,1,2])
print(ary)

[0 1 2]


In [7]:
# 都知道根源是「類別類」，所以它然可以使用class去呼叫，話說這邊也就是Static fuction
import numpy
ary = numpy.array([0])
print(ary)

[0]


In [19]:
import numpy as np

ary1 = np.array([0,1,2])
ary2 = numpy.array([0])
print(type(ary1))        #type() => check the parameter reference data type
print(type(ary2))        #cant see that, these ary1、2 output the same reference class => since it just alias, and it is class type 
print(ary1.shape)        #shape() => 並非回傳長度，而是回傳「陣列的維度」，每個維度的大小
print(ary2.shape)        #(n,) => refer維度為一，且一維的大小為n；(n,m) => 
ary3 = np.array([        #(n,m) => 表示二維，一維資料長度「皆」為n、二維每筆皆為m
    [0,1,2],          # NOTE: Numpy是「normal matrix」，「每個維度之間」自己的結構(長度)必須一致
    [3,4,5],
    [6,7,8]
])
print(ary3.shape)

#以下為「相同維度之間，長度不一」的寫法
# ary4 = np.array([      
#     [0,1,2,4],          #這裡一維向量，有些結構(長度)為4，也些為3 =>就不行
#     [3,4,5],
#     [6,7,8]
# ])

# 最後就是這邊一樣可以用index store element, also index start from zero
print(ary1[0])
print(ary1[1])
# how about when indexOutOfBound
# print(ary2[1])    #ok也不行



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(3,)
(1,)
(3, 3)
0
1


In [22]:
import numpy as np

ary1 = np.array([0,1,2])
ary2 = np.array([        
    [0,1,2],          
    [3,4,5],
    [6,7,8]
])
print(ary1.ndim)        #ndime => return dimension,回傳陣列為度
print(ary2.ndim)

1
2


In [3]:
# reshape() => 重新調整結構
import numpy
ary = numpy.array([1,2,3,4,5,6])
print(ary)
reshapedAry1 = ary.reshape(2,3)
print(reshapedAry1)
reshapedAry2 = ary.reshape(3,2)
print(reshapedAry2)
# oh對了，python variable沒有declare這個動作，address&assign都是靠value去做的，

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
